### PR TITLE
Add some standard small fiducials, 1mm copper, 2.54mm keepout

### PR DESCRIPTION
**Pull request by hzeller**
For top and bottom copper.

The other Fiducials in this library are _huge_ and are not really useful for small boards.

A 1mm copper fiducial is pretty standard and can be recognized by typical Pick'n Place machines. The keepout with an outer diameter of 2.54mm makes sure that the contrast is good and also a nice size to fit into typical grids.

These fiducials are coherent with suggestions in this Ladyada article:
http://www.ladyada.net/library/pcb/fiducials.html

### CODE REVIEW

**Comment by odurc** [comment]
Hi. Please, check your footprints with [check_kicad_mod](https://github.com/KiCad/kicad-library-utils/blob/master/pcb/check_kicad_mod.py) script, I guess, in the fiducial case, not all KLC Rules is applicable, but some of them are.

**Comment by hzeller** [comment]
Ah, nice script!
Ok, fixed 10.2 violation (there was no description yet) and 10.4 (for Value I had choosen a prettier just 'Fiducial' text, but it requires the full name length).

Remaining:
checking module: Fiducial_1mm_Dia_2.54mm_Outer_CopperBottom
  Violating Rule 10.5
  Violating Rule 10.6
  Violating Rule 6.3
  Violating Rule 6.6
checking module: Fiducial_1mm_Dia_2.54mm_Outer_CopperTop
  Violating Rule 10.5
  Violating Rule 10.6
  Violating Rule 6.3
  Violating Rule 6.6

The script also complains a bout 10.5 and 10.6, but there are no other properties set, so they should be default, no ?

Then it complains about 6.3, which requires for through-hole components to have the anchor on pin 1. This is not a through-hole component, and also there is only one ~ pin, so this doesn't apply.

It complains about 6.6  (Courtyard line ...), but I don't know what that means, please advise.

**Comment by michal777** [comment]
According to https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt

6.3, 10.5 - in footprint properties you left attributes normal (THT) and the script says it's wrong because you have no THT pads. In this case attributes should be set to virtual (see kicad manual).

10.6 - in this case ignore it, setting mask margin is necessary for this footprint (usually is odd).
6.6 - courtyard is a bounding box, helps placing components so that distances between them are not too small. Examples: Capacitors_ThroughHole.pretty, Housings_SOIC.pretty.

**Comment by michal777** [comment]
10.6 - alternatively, to get clear logs from library cleaners, mask can be added as circle (like in other fiducials in this library) and pad properties can be default.

**Comment by hzeller** [comment]
Alright, added
- attbributes virtual
- courtyard (I think it is actually useful for the fiducial to make sure nothing is obstructing the view)

Still getting complaints:
checking module: Fiducial_1mm_Dia_2.54mm_Outer_CopperTop
  Violating Rule 10.5
  Violating Rule 10.6

I didn't add a mask circle as I think the 'builtin' mask of the pad is a nicer and more robust way (The other Fiducials in this library are as well complained about this). I still get 10.5, even though the attributes are now set to 'virtual' (but 6.3 vanished).

checking module: Fiducial_1mm_Dia_2.54mm_Outer_CopperBottom
  Violating Rule 10.5
  Violating Rule 10.6
  Violating Rule 6.6

This is odd. I has the same courtyard as the other one (0.05mm), but on the bottom side (because that is where the pad is). Could it be that the script always assumes that the courtyard needs to be on the 'top' side ?

**Comment by michal777** [comment]
10.5, 10.6 are probably ok but the script doesn't accept "virtual" and complains about not default mask margin.
6.6 - the courtyard as described in the rule should have clearance 0.25mm and be rounded to 0.05 (IPC7351, level B).

**Comment by hzeller** [comment]
The funny thing is, that the script only complains for the bottom pad in the courtyard case, not the top pad.

Re-reading that section, I probably made two mistakes
- I made a circular courtyard (which sounded appropriate in this case). However, since it needs to be 'on a grid of 0.05mm'. Does that imply that a courtyard is always rectangular ?
- The radius of the courtyard was 1.27mm, which is not on that grid.

However, I tried to have a radius of 1.3mm and a I tried to have a square with 1.3mm around (both with 0.05mm line thickness), but both cases are still complained about in the script about item 6.6 for the CopperBottom case.

In the meantime, the CopperTop version of the fiducial passes fine with a circle with 1.27mm radius.

I suspect that the script only looks at F.CrtYd, while in the CopperBottom case, the courtyard is in B.CrtYd ?

What would be the 'most correct' way in this case ? Am I right that I probably have to make it a square around the pin, or does circular work ?

(I don't have access to a copy of IPC7351, sorry for the detailed questions)

**Comment by michal777** [comment]
I think that circular courtyard must be allowed in kicad libraries, square courtyards would waste too much space in some cases so the rounding to 0.05 mm is impossible. I don't know if IPC7351 addresses this problem, IPC7351 is for smd, the draft for tht:
http://www.ipc.org/committee/drafts/1-13_d_7251WD1.pdf
says: Courtyard contours to shape of component body and/or lands
so the circular is ok.

**Comment by hzeller** [comment]
Ok, I kept the circular courtyard, but rounded the radius to the grid from 1.27 radius to 1.3.

**Comment by hzeller** [comment]
Is there anything else I can do, or is this ready to merge ?

**Comment by michal777** [comment]
Merged. I've corrected is the courtyard - added 0.25 mm clearance (rule 6.6).

**Pull request merged**
